version: '3.4'

services:
  gsapapp:
    image: streami-fi
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
